# Generated by Django 5.1.15 on 2026-07-28 02:11

import apps.accounts.models
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_schema_20260727'),
    ]

    operations = [
        # The column type does not exist until the extension is installed.
        CITextExtension(),
        # NOTE for any environment with real data: this rebuilds the unique
        # index case-insensitively, so it fails if two accounts already differ
        # only by capitalisation. Merge or rename those rows first.
        migrations.AlterField(
            model_name='user',
            name='email',
            field=apps.accounts.models.CaseInsensitiveEmailField(max_length=254, unique=True),
        ),
    ]
