# Generated by Django 5.1.15 on 2026-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_case_insensitive_email_20260727'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
