# Generated by Django 5.1.15 on 2026-07-28 18:26

import apps.accounts.models
from django.db import migrations, models


def copy_display_zone_to_scheduling(apps_registry, schema_editor):
    """Existing providers authored their hours in whatever their user zone was.

    Recording that explicitly rather than leaving it to the blank-string
    fallback means a later change to the display zone cannot retroactively
    reinterpret hours that were written before the two were separated.
    """
    ProviderProfile = apps_registry.get_model('accounts', 'ProviderProfile')
    for profile in ProviderProfile.objects.select_related('user').iterator():
        if not profile.scheduling_timezone:
            profile.scheduling_timezone = profile.user.timezone
            profile.save(update_fields=['scheduling_timezone'])


def noop(apps_registry, schema_editor):
    """Reversing just drops the column; nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_provider_location_20260728'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='scheduling_timezone',
            field=models.CharField(blank=True, max_length=64, validators=[apps.accounts.models.validate_timezone]),
        ),
        migrations.RunPython(copy_display_zone_to_scheduling, noop),
    ]
